[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/ru"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/ru/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/ru/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/ru/pricing.html"
  to = "/pricing.html"
  status = 301
  force = true

[[redirects]]
  from = "/ru/procedures.html"
  to = "/procedures.html"
  status = 301
  force = true

[[redirects]]
  from = "/ru/indications.html"
  to = "/indications.html"
  status = 301
  force = true

[[redirects]]
  from = "/ru/nutrition.html"
  to = "/nutrition.html"
  status = 301
  force = true

[[redirects]]
  from = "/ru/licenses.html"
  to = "/licenses.html"
  status = 301
  force = true

[[redirects]]
  from = "/ru/contact.html"
  to = "/contact.html"
  status = 301
  force = true

[[redirects]]
  from = "/ru/about.html"
  to = "/about.html"
  status = 301
  force = true

[[redirects]]
  from = "/ru/rooms.html"
  to = "/rooms.html"
  status = 301
  force = true
